version: "3.9"

services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    working_dir: /app/apps
    command: ["python", "app.py"]
    volumes:
      - .:/app  # Optional: for live code changes in dev
    restart: unless-stopped
